<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smt2</string>
	</array>
	<key>name</key>
	<string>SMT-LIB 2.0</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#commands</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()\s*(set-logic)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#simpleSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(set-option)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(set-info)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(declare-sort)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#simpleSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numerals</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(define-sort)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(declare-fun|declare-const)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(define-fun|define_cons)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(push)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numerals</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(pop)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numerals</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(assert)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(check-sat)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#simpleSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedSymbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-assertions)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-proof)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(exit)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(reset)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-unsat-core)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-value)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-assignment)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-model)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-option)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(get-info)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()\s*(echo)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.smt2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.smt2</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.smt2</string>
		</dict>
		<key>consts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Decimals.</string>
					<key>match</key>
					<string>\b(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)</string>
					<key>name</key>
					<string>constant.other.smt2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numerals</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Hexadecimals.</string>
					<key>match</key>
					<string>#x\h+</string>
					<key>name</key>
					<string>constant.other.smt2</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Binarys.</string>
					<key>match</key>
					<string>#b(0|1)+</string>
					<key>name</key>
					<string>constant.other.smt2</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>String literals.</string>
					<key>match</key>
					<string>\"(\\\"|[^\"])*\"</string>
					<key>name</key>
					<string>constant.other.smt2</string>
				</dict>
			</array>
		</dict>
		<key>convenienceSymbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Propositional and =.</string>
					<key>match</key>
					<string>(\b(true|false|and|or|ite|not)\b)|((=&gt;|=)\s)</string>
					<key>name</key>
					<string>keyword.smt2</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arithmetic.</string>
					<key>match</key>
					<string>[&lt;&gt;[&lt;=][&gt;=]\+\-\*/]\s</string>
					<key>name</key>
					<string>keyword.smt2</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Pritive types.</string>
					<key>match</key>
					<string>\b(Bool|Int|Real)\b</string>
					<key>name</key>
					<string>support.type.smt2</string>
				</dict>
			</array>
		</dict>
		<key>indexed</key>
		<dict>
			<key>begin</key>
			<string>(\()\s*(_)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.smt2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.smt2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Indexing on quoted.</string>
			<key>end</key>
			<string>((([1-9][0-9]*)\s*)+)(\))|(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.smt2</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.smt2</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.smt2</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simpleSymbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotedSymbols</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\)]*</string>
					<key>name</key>
					<string>invalid.smt2</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>:[\w~!@\$%\^&amp;\*\-\+=&lt;&gt;\.\?/]+</string>
			<key>name</key>
			<string>keyword.smt2</string>
		</dict>
		<key>numerals</key>
		<dict>
			<key>match</key>
			<string>\b(0|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.other.smt2</string>
		</dict>
		<key>quotedSymbols</key>
		<dict>
			<key>begin</key>
			<string>(\|)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.smt2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\|)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.smt2</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hilight backslash because illegal.</string>
					<key>match</key>
					<string>\\</string>
					<key>name</key>
					<string>invalid.smt2</string>
				</dict>
			</array>
		</dict>
		<key>reserved</key>
		<dict>
			<key>match</key>
			<string>\b(par|STRING|DECIMAL|NUMERAL|_|as|let|forall|exists)\b|!</string>
			<key>name</key>
			<string>constant.numeric.other.smt2</string>
		</dict>
		<key>simpleSymbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[~@\$%\^&amp;\*\-\+=&lt;&gt;\.\?/][~!@\$%\^&amp;\*\-\+=&lt;&gt;\.\?/\w]*</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Word separator if starting by alpha.</string>
					<key>match</key>
					<string>\b[a-zA-Z][~!@\$%\^&amp;\*\-\+=&lt;&gt;\.\?/\w]*</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>_ and ! are reserved.</string>
					<key>match</key>
					<string>[!_][~!@\$%\^&amp;\*\-\+=&lt;&gt;\.\?/\w]+</string>
				</dict>
			</array>
		</dict>
		<key>terms</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#consts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#convenienceSymbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#simpleSymbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quotedSymbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#indexed</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reserved</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#terms</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>For annotations.</string>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s\)]</string>
							<key>name</key>
							<string>invalid.smt2</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>smt2</string>
	<key>uuid</key>
	<string>bc1d9256-66de-45e3-8be6-813b26a05a7c</string>
</dict>
</plist>
